### ISSUE TITLE
Job for tomcat.service failed because the control process exited with error code.

### ISSUE THREAD

**Issue by Kreijstal** [rgiyf/tomcatScript#1]
See "systemctl status tomcat.service" and "journalctl -xe" for details.
Well `systemctl status tomcat.service` outputs
```
● tomcat.service - Apache Tomcat Web Application Container
   Loaded: loaded (/etc/systemd/system/tomcat.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since sáb 2018-03-17 08:37:00 -05; 2min 26s ago

mar 17 08:37:00 compres-server systemd[1]: Starting Apache Tomcat Web Application Container...
mar 17 08:37:00 compres-server systemd[1]: tomcat.service: Control process exited, code=exited status=203
mar 17 08:37:00 compres-server systemd[1]: Failed to start Apache Tomcat Web Application Container.
mar 17 08:37:00 compres-server systemd[1]: tomcat.service: Unit entered failed state.
mar 17 08:37:00 compres-server systemd[1]: tomcat.service: Failed with result 'exit-code'.

```
`journalctl -xe` doesn't output any relevant information. I did run as sudo, as I was prevented from running it as regular user.

**Comment by probwebdev** [comment]
@Kreijstal Hi! This script is not used for a long time and it's pretty dumb anyway. 
I would recommend you to use Docker for your applications.
If you still want to use this script only thing I can advise is to google this error code _tomcat.service: Control process exited, code=exited status=**203**_
Good luck.
